name: Build Windows EXE

on:
  push:
    branches: [ main ]           # lance à chaque push sur main
  workflow_dispatch:             # ou déclenchement manuel

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Récupère le code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configure Python 3.10 (ou la version que tu utilises)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Installe les dépendances (requirements + PyInstaller)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # 4. Construit l’exécutable unique, mode GUI
    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --name SimulationResidence main.py

    # 5. Charge l’artefact dans l’onglet Actions
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SimulationResidence.exe
        path: dist/SimulationResidence.exe